### ISSUE TITLE
Seeing error - panic: runtime error: index out of range [7] with length 1 - while processing my example.csv

### ISSUE THREAD

**Issue by ankitanallana-livongo** [asoorm/hey-hdr#3]
When I try to generate the HDR file - the program abruptly exits with an error:
```
% cat example.csv | go run hey-hdr.go
panic: runtime error: index out of range [7] with length 1

goroutine 1 [running]:
main.main()
	/Users/ankita.nallana/hey-hdr/hey-hdr.go:62 +0x173d
exit status 2
```
Unsure why I'm seeing this - my `example.csv` was properly generated (without any issues) from `hey`

**Comment by asoorm** [comment]
Interesting - could you provide the output of `head example.csv`?

Does it look similar to this with 8 columns and a bunch of rows?

```
head example.csv
response-time,DNS+dialup,DNS,Request-write,Response-delay,Response-read,status-code,offset
0.0156,0.0052,0.0033,0.0000,0.0094,0.0001,200,0.0104
0.0144,0.0051,0.0039,0.0000,0.0091,0.0002,200,0.0117
0.0158,0.0057,0.0035,0.0001,0.0098,0.0001,200,0.0104
0.0155,0.0050,0.0037,0.0000,0.0098,0.0000,200,0.0108
0.0221,0.0059,0.0047,0.0000,0.0159,0.0002,200,0.0110
0.0218,0.0048,0.0035,0.0000,0.0169,0.0001,200,0.0116
0.0212,0.0045,0.0034,0.0000,0.0166,0.0002,200,0.0124
0.0242,0.0049,0.0036,0.0000,0.0191,0.0001,200,0.0122
0.0251,0.0058,0.0038,0.0001,0.0192,0.0001,200,0.0117
```
Does it work with the example.csv in the root of this repository? https://raw.githubusercontent.com/asoorm/hey-hdr/master/example.csv

**Comment by ankitanallana-livongo** [comment]
I'm sorry, my example.csv was differently generated (different from what you mentioned in your comment) - I ran `hey` and `hey-hdr` again and I see proper result. Thank you so much for this tool! Really helps me understand my application/server performance better!
